CREATE TABLE Questions (
    id VARCHAR(255) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    tried TEXT NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    created_at DATETIME2 DEFAULT GETDATE() NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);
